name: Dump github.event

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event JSON
        run: |
          echo '${{ toJson(github) }}' | jq .
      - name: Print GitHub select data
        run: |
          echo 'repo,branch,actor,pusher,sender'
          echo '${{github.repository}},${{github.ref_type}} ${{github.ref_name}},${{github.actor}},${{github.event.pusher.name}},${{github.event.sender.login}}'
